name: CI

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
    branches:
    - main
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      PKGVER: $GITHUB_REF_NAME

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore
      # can't use locked mode due to https://github.com/NuGet/Home/issues/9195
      run: dotnet restore # --locked-mode

    - name: Test
      run: dotnet test --no-restore -c $BUILD_CONFIG /p:AltCover=true /p:AltCoverCobertura=coverage.xml /p:AltCoverAssemblyFilter="(.*)(?<!Mntnr.Toolkit)$"

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.2.0
      with:
        filename: tests/coverage.xml

    - name: Pack
      run: dotnet pack --no-restore -c $BUILD_CONFIG /p:Version=$PKGVER
      
    - name: Publish
      if: startsWith(github.ref, 'refs/tags/')
      run: nuget push -s https://api.nuget.org/v3/index.json -ApiKey ${{secrets.NUGET_API_KEY}}
      
      
      
