name: CI

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
    branches:
    - main
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      NUGET_OUT_DIR: ./.pkg

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore
      run: dotnet restore # --locked-mode # disabled due to https://github.com/NuGet/Home/issues/9195

    - name: Test
      run: dotnet test --no-restore -c $BUILD_CONFIG /p:AltCover=true /p:AltCoverCobertura=coverage.xml /p:AltCoverAssemblyFilter='(.*)(?<!mntnr.toolkit)$'

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.2.0
      with:
        filename: tests/coverage.xml

    - name: Pack
      if: startsWith(github.ref, 'refs/tags/')
      run: dotnet pack --no-restore -c $BUILD_CONFIG /p:Version=$GITHUB_REF_NAME -o $NUGET_OUT_DIR
      
    - name: Publish
      if: startsWith(github.ref, 'refs/tags/')
      run: nuget push -Source https://api.nuget.org/v3/index.json -ApiKey ${{secrets.NUGET_API_KEY}} $NUGET_OUT_DIR/*.nupkg
